### ISSUE TITLE
Issue running remora

### ISSUE THREAD

**Issue by themoah** [zalando-incubator/remora#5]
Hi,

I've tried to run, but on sbt docker:publishLocal I've received exception:
`[info] Done packaging.
[error] Error response from daemon: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
java.lang.RuntimeException: Nonzero exit value: 1
        at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:296)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$14.apply(DockerPlugin.scala:109)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$14.apply(DockerPlugin.scala:108)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (docker:publishLocal) Nonzero exit value: 1
[error] Total time: 15 s, completed May 28, 2017 6:04:19 PM`

Tried to run from Intellij, but request to http://localhost:9000/consumers returned _ Internal Error! Please check logs _
exception:
`[remora-akka.actor.default-dispatcher-7] DEBUG akka.io.TcpListener - Successfully bound to /0:0:0:0:0:0:0:0:9000
[remora-akka.actor.default-dispatcher-7] DEBUG akka.io.TcpListener - New connection accepted
[remora-akka.actor.default-dispatcher-6] ERROR a.actor.ActorSystemImpl - Request received an exception: Timeout length must be positive, question not sent to [Actor[akka://remora/user/kafka-client-actor#-1606370397]]. Sender[null] sent the message of type "KafkaClientActor$ListConsumers$".
java.lang.IllegalArgumentException: Timeout length must be positive, question not sent to [Actor[akka://remora/user/kafka-client-actor#-1606370397]]. Sender[null] sent the message of type "KafkaClientActor$ListConsumers$".
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:292)
	at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:281)
	at Api.Api$$askFor(Api.scala:51)
	at Api$$anonfun$2$$anonfun$apply$2$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(Api.scala:64)
	at Api$$anonfun$2$$anonfun$apply$2$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(Api.scala:64)`

What I'm doing wrong ?

**Comment by imduffy15** [comment]
Hey AD,

Thanks for opening this issue. I've a PR opened to fix this for you.

If you use the 0.2.0 tag (https://github.com/zalando-incubator/remora/releases) it should run without issue.

Hope you've had a good weekend, if there's anything else you need help with just let us know.

Thanks,
Ian.

**Comment by marky-mark** [comment]
Re: Issue with Docker (Should have been a separate issue tbh) but anyway i think its due to building a lot of docker containers, you might need to clear out your docker images e.g. https://techoverflow.net/2013/10/22/docker-remove-all-images-and-containers/

Or else some solutions on[ google regarding the error ](https://www.google.ie/search?q=Error+response+from+daemon%3A+An+operation+on+a+socket+could+not+be+performed+because+the+system+lacked+sufficient+buffer+space+or+because+a+queue+was+full.+java.lang.RuntimeException&oq=Error+response+from+daemon%3A+An+operation+on+a+socket+could+not+be+performed+because+the+system+lacked+sufficient+buffer+space+or+because+a+queue+was+full.+java.lang.RuntimeException&aqs=chrome..69i57.495j0j4&sourceid=chrome&ie=UTF-8)
