### ISSUE TITLE
finding remora logs & using kafka 2.2.0 

### ISSUE THREAD

**Issue by arnoldyahad** [zalando-incubator/remora#67]
im getting a message to check the logs in the container 

```
curl http://localhost:9000/consumers/my_topic 
Internal Error! Please check logs
```
i tried to find it inside the container 
```
docker exec -it root_remora-streams_1 /bin/bash

/opt/docker/logs$ ls -ll
total 0
```

any idea where i can see the logs?
im trying to use remora on my 2.2.0 kafka cluster, on 2.1.0 it works just fine.

**Comment by marky-mark** [comment]
Hi,

Looking into the issue now

**Comment by arnoldyahad** [comment]
hi @marky-mark  i see that when we use our staging cluster - which is 2.2.0 also - it doesnt happen
so its not version related.

can you elaborate on what occasion the api that sent to consumers/<topic_name> will return 500? a missing field in the json?

we also started getting metrics about 20 hours later but when we restarted the container - its gone again. may it have something to do with kafka networking?

**Comment by marky-mark** [comment]
if you do the following, can you see them?

```
docker logs root_remora-streams_1
```

**Comment by arnoldyahad** [comment]
the errors from docker logs root_remora-streams_1  :
(this is when quering the consumers/<topic_name>)

```
2019-04-23 12:24:19,562 - [ERROR] - [remora-akka.actor.default-dispatcher-4650] akka.actor.ActorSystemImpl - Request received an exception: null
java.lang.NullPointerException: null
	at scala.Predef$.Long2long(Predef.scala:363)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$getLogEndOffsets$1.apply(ConsumerGroupCommand.scala:357)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$getLogEndOffsets$1.apply(ConsumerGroupCommand.scala:355)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService.getLogEndOffsets(ConsumerGroupCommand.scala:355)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService.describePartitions(ConsumerGroupCommand.scala:290)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService.kafka$admin$ConsumerGroupCommand$ConsumerGroupService$$collectConsumerAssignment(ConsumerGroupCommand.scala:270)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$5$$anonfun$8.apply(ConsumerGroupCommand.scala:316)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$5$$anonfun$8.apply(ConsumerGroupCommand.scala:310)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$5.apply(ConsumerGroupCommand.scala:310)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$$anonfun$5.apply(ConsumerGroupCommand.scala:303)
	at scala.Option.map(Option.scala:146)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService.collectGroupOffsets(ConsumerGroupCommand.scala:303)
	at kafka.admin.RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1$$anonfun$apply$3.apply(RemoraKafkaConsumerGroupService.scala:72)
	at kafka.admin.RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1$$anonfun$apply$3.apply(RemoraKafkaConsumerGroupService.scala:69)
	at nl.grons.metrics.scala.Timer.time(Timer.scala:54)
	at kafka.admin.RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1.apply(RemoraKafkaConsumerGroupService.scala:69)
	at kafka.admin.RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1.apply(RemoraKafkaConsumerGroupService.scala:69)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by marky-mark** [comment]
Does the topic name exist?

**Comment by arnoldyahad** [comment]
im closing the issue because it probably on our side ( and the answer on the logs has been given) thanks a lot
